### ISSUE TITLE
change the header 

### ISSUE THREAD

**Issue by PrasadSAmbekar** [nirravv/Hospital-Management-Html#9]
header file is not well as it is the important part to attract the people.
you must add this header information to footer , AND make head more smooth

**Comment by AdityaB09** [comment]
In header section, unity image was not aligned with the other contents of the navigation bar. 
Add **style="margin-top:-10px;"**  in the <ul></ul> tag with class name : 'nav navbar-nav' of all the relevant files

 <ul class="nav navbar-nav" style="margin-top:-10px;">
